# Generated by Django 4.1.5 on 2023-01-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprodile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProdile',
            new_name='UserProfile',
        ),
    ]
